# Generated by Django 3.1.2 on 2020-11-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_main',
            field=models.IntegerField(blank=True, default=0, verbose_name='Main Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Second Last Name'),
        ),
    ]
