# Generated by Django 3.1.2 on 2020-12-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201129_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN_DPE', 'Administrador DPE'), ('CLIENT_MAIN', 'Cliente Matriz'), ('CLIENT', 'Cliente Sucursal')], default='CLIENT', max_length=50, verbose_name='Type'),
        ),
    ]
