# Generated by Django 3.1.2 on 2020-10-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company identifier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN_DPE', 'Admin_dpe'), ('CLIENT_MAIN', 'Client_main'), ('CLIENT', 'Client')], default='CLIENT', max_length=50, verbose_name='Type'),
        ),
    ]
