# Generated by Django 3.1.2 on 2020-10-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201027_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_id',
            new_name='uci',
        ),
    ]
