# Generated by Django 3.1.2 on 2020-11-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_second_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.IntegerField(blank=True, max_length=255, verbose_name='Company'),
        ),
    ]
