# Generated by Django 3.1.2 on 2020-11-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201117_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.IntegerField(blank=True, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of user'),
        ),
    ]
