# Generated by Django 3.1.2 on 2021-01-19 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('MAIN', 'Main'), ('BRANCH', 'Branch')], default='MAIN', max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_contact', models.CharField(blank=True, max_length=255)),
                ('company_phone', models.CharField(blank=True, max_length=255)),
                ('company_email', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='TestCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('CIE', 'CIE'), ('DPECON', 'DPECon')], max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('activate', models.BooleanField(default=True)),
                ('expiration', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.testcatalog')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.testcatalog')),
            ],
        ),
    ]
