# Generated by Django 3.1.2 on 2021-02-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210119_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcatalog',
            name='test_name',
            field=models.CharField(choices=[('CIE', 'CIE'), ('Integridad', 'Integridad')], max_length=128),
        ),
        migrations.AlterField(
            model_name='testcode',
            name='code',
            field=models.CharField(max_length=60),
        ),
    ]
