# Generated by Django 3.1.2 on 2020-11-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201125_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='email',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='phone',
            new_name='company_phone',
        ),
        migrations.AddField(
            model_name='company',
            name='company_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='company_main',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
