# Generated by Django 3.1.2 on 2021-03-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210315_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcatalog',
            name='test_name',
            field=models.CharField(choices=[('CIE', 'CIE'), ('Integridad', 'Integridad'), ('Max', 'Max')], max_length=128),
        ),
        migrations.AlterField(
            model_name='testcode',
            name='seconds_integrity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
