# Generated by Django 3.1.5 on 2021-01-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcie',
            name='nombre',
            field=models.CharField(default='', help_text='Nombre completo del candidato', max_length=50),
        ),
        migrations.AddField(
            model_name='objectcie',
            name='profesion',
            field=models.CharField(default='', help_text='Profesion del candidato', max_length=50),
        ),
    ]
