# Generated by Django 3.1.5 on 2021-01-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210125_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcie',
            name='edad',
            field=models.IntegerField(default=1, help_text='Edad del candidato'),
        ),
        migrations.AddField(
            model_name='objectcie',
            name='estado',
            field=models.CharField(default='', help_text='Estado de nacimiento del candidato', max_length=50),
        ),
        migrations.AddField(
            model_name='objectcie',
            name='rfc',
            field=models.CharField(default='', help_text='RFC del candidato', max_length=50),
        ),
        migrations.AddField(
            model_name='objectcie',
            name='sexo',
            field=models.CharField(default='', help_text='Sexo del candidato', max_length=50),
        ),
    ]
