# Generated by Django 3.1.5 on 2021-01-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210119_0257'),
        ('tests', '0003_auto_20210125_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcie',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.testcode'),
        ),
    ]
