# Generated by Django 3.1.2 on 2021-02-02 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_objectcie_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
