# Generated by Django 3.1.5 on 2021-02-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20210201_2353'),
        ('tests', '0005_objectcie_created'),
    ]

    operations = [
    ]
