# Generated by Django 3.1.2 on 2021-02-03 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_merge_20210202_2351'),
        ('tests', '0006_merge_20210202_0533'),
    ]

    operations = [
    ]
