# Generated by Django 3.1.2 on 2021-02-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_merge_20210203_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectcie',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='objectcie',
            name='rfc',
        ),
    ]
