# Generated by Django 3.1.2 on 2021-02-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20210205_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectcie',
            name='profesion',
        ),
        migrations.AddField(
            model_name='objectcie',
            name='email',
            field=models.CharField(default='', help_text='Email del candidato', max_length=50),
        ),
    ]
