# Generated by Django 3.1.5 on 2021-02-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_merge_20210209_0242'),
        ('tests', '0009_auto_20210205_2254'),
    ]

    operations = [
    ]
