# Generated by Django 3.1.2 on 2021-02-13 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210213_0209'),
        ('tests', '0010_merge_20210210_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectIntegrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', help_text='Nombre completo del candidato', max_length=50)),
                ('age', models.IntegerField(default=1, help_text='Edad del candidato')),
                ('email', models.CharField(default='', help_text='Email del candidato', max_length=50)),
                ('sex', models.CharField(default='', help_text='Sexo del candidato', max_length=50)),
                ('adictions', models.IntegerField(default=0, help_text='adicciones')),
                ('judgement', models.IntegerField(default=0, help_text='juicio')),
                ('discipline', models.IntegerField(default=0, help_text='disciplina')),
                ('verecity', models.IntegerField(default=0, help_text='verecidad')),
                ('loyalty', models.IntegerField(default=0, help_text='lealtad')),
                ('intentionality', models.IntegerField(default=0, help_text='intencionalidad')),
                ('ethic', models.IntegerField(default=0, help_text='etica')),
                ('reliability', models.IntegerField(default=0, help_text='seguridad')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.testcode')),
            ],
        ),
    ]
