# Generated by Django 3.1.2 on 2021-02-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_objectintegrity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectintegrity',
            old_name='verecity',
            new_name='veracity',
        ),
    ]
