# Generated by Django 3.1.2 on 2021-03-28 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210324_0544'),
        ('tests', '0014_maxpositions'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxpositions',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
